### PR TITLE
Add steering committee responsibility

### PR DESCRIPTION
**Pull request by rnjudge**
add bullet to steering committee responsibilities regarding overseeing disbursement of any available funding

### CODE REVIEW

**Comment by rnjudge** [comment]
cc @kestewart @zvr @jlovejoy @swinslow @goneall also Phil and Bob who I cannot find GitHub handles for

**Review by bobmartin3000 — APPROVED** [review]
Looks good.

**Review by goneall — APPROVED** [review]
LGTM

**Review by swinslow — APPROVED** [review]
+1 from me

@mkdolan, since amendments to the SPDX governance are subject to approval by the LF, are you good with this addition? Happy to discuss if any questions.

**Review by zvr — APPROVED** [review]

**Comment by mkdolan** [comment]
+1

**Comment by jlovejoy** [comment]
+1 to me. I added a description of the PR as well

**Pull request merged**
