### PR TITLE
update governance as to Team Lead nominations

### PR DESCRIPTION
**Pull request by jlovejoy**
re-order items

### CODE REVIEW

**Comment by swinslow** [comment]
Looks to me like this is just rearranging, to make it explicit that the "After discussion with the nominees...." bit applies to both Team Leads and Chair nominations. Is that the intent? If so, +1 from me, seems fine to clarify.

**Review by seabass-labrax — APPROVED** [review]
Here's my approval; we might be able to get quorum on this asynchronously :smiley:

**Review by kestewart — APPROVED** [review]
+1 from me

**Review by goneall — APPROVED** [review]
LGTM

**Comment by jlovejoy** [comment]
discussed and voted on May 31st Steering Committee call, all in favor (8 present in meeting in favor, plus Steve via comment above)

**Comment by swinslow** [comment]
@mkdolan this is a minor cleanup and clarification on the process for nominations to Team Leads, can you give a +1 from the LF's side?

**Comment by mkdolan** [comment]
+1 Steve.

**Comment by jlovejoy** [comment]
thanks!

**Pull request merged**
