### PR TITLE
Update 5._Governance.md

### PR DESCRIPTION
**Pull request by jlovejoy**
Add explicit statement regarding adding Team Leads (up to 3)

NOTE: changes to governance need 2/3 approval of SC members and subject to approval by Linux Foundation as per section 3.4

### CODE REVIEW

**Comment by swinslow** [comment]
Thanks @jlovejoy! +1 from me, I think this reflects the intent of the existing structure, and resolves an ambiguity about whether new Team Leads are only appointed upon expiration of term / resignation.

**Comment by jlovejoy** [comment]
discussed on May 10th SC call: approved by all Steering Committee members in attendance (not counting one absence)

**Comment by swinslow** [comment]
@mkdolan as mentioned above, changes to the SPDX governance are subject to approval by the LF. The SPDX Steering Committee has approved, can you give a +1 from the LF side?

**Comment by mkdolan** [comment]
+1 for the LF

**Comment by swinslow** [comment]
Thanks all! Merging now.

**Pull request merged**
